/**
 * HMAC cross-validation against the main-engine Python `security.py`.
 *
 * The expected signatures below were generated by the actual Python implementation
 * (`app/core/security.py` `compute_signature`), so these vectors prove byte-for-byte
 * compatibility rather than self-consistency.
 */
import { describe, expect, it } from 'vitest';
import {
  buildCanonicalString,
  computeSignature,
  constantTimeEqual,
  sha256Hex,
  signRequest,
  verifyRequest
} from '../src/auth/hmac.js';
import { ERROR_CODES } from '../src/errors.js';

const SECRET = 'test-secret';
const KEYS = { 'cf-hotspot-v1': SECRET };

describe('cross-validation against Python security.py', () => {
  it('matches vector 1 (qualified-events)', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    expect(body.byteLength).toBe(7);
    const sha = await sha256Hex(body);
    expect(sha).toBe('015abd7f5cc57a2dd94b7590f04ad8084273905ee33ec5cebeae62276a97f862');

    const canonical = buildCanonicalString(
      'POST',
      '/api/v1/inbound/qualified-events',
      '2026-08-30T10:00:00Z',
      '92dc1749-4d96-4f32-b76b-7cbcd730ac07',
      sha,
      7
    );
    expect(canonical).toBe(
      'POST\n/api/v1/inbound/qualified-events\n2026-08-30T10:00:00Z\n' +
        '92dc1749-4d96-4f32-b76b-7cbcd730ac07\n' +
        '015abd7f5cc57a2dd94b7590f04ad8084273905ee33ec5cebeae62276a97f862\n7'
    );

    const sig = await computeSignature(SECRET, canonical);
    expect(sig).toBe('v1=27bef8a89ac660073613619829316e98b8c9eac08a2a7429c3dd7af9ebbdc860');
  });

  it('matches vector 2 (hotspot-candidates, compact JSON)', async () => {
    const body = new TextEncoder().encode('{"event":"hotspot","rank":3}');
    expect(body.byteLength).toBe(28);
    const sha = await sha256Hex(body);
    expect(sha).toBe('c178dc24a9880ce35e166fcd26f5eb697bc09d542233125c588918c283a2338f');

    const canonical = buildCanonicalString(
      'POST',
      '/api/v1/hotspot-candidates',
      '2026-08-30T11:22:33Z',
      '3f2504e0-4f11-11e8-9c2d-fa7ae01bbebc',
      sha,
      28
    );
    const sig = await computeSignature(SECRET, canonical);
    expect(sig).toBe('v1=d1640e91bd304b12232eff9e6061a73f67bdadda8984b378510ea17315d3dfd1');
  });
});

describe('sha256Hex', () => {
  it('hashes a string and bytes identically', async () => {
    const s = '{"a":1}';
    expect(await sha256Hex(s)).toBe(await sha256Hex(new TextEncoder().encode(s)));
  });

  it('handles a subarray view correctly (byteOffset trap)', async () => {
    const backing = new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]);
    const view = backing.subarray(1, 4); // [2,3,4]
    const full = new Uint8Array([2, 3, 4]);
    expect(await sha256Hex(view)).toBe(await sha256Hex(full));
  });
});

describe('constantTimeEqual', () => {
  it('returns true for equal strings', () => {
    expect(constantTimeEqual('abc', 'abc')).toBe(true);
  });
  it('returns false for different strings of same length', () => {
    expect(constantTimeEqual('abc', 'abd')).toBe(false);
  });
  it('returns false for different lengths', () => {
    expect(constantTimeEqual('abc', 'ab')).toBe(false);
    expect(constantTimeEqual('ab', 'abc')).toBe(false);
  });
  it('returns false for empty vs non-empty', () => {
    expect(constantTimeEqual('', 'a')).toBe(false);
  });
});

describe('verifyRequest end-to-end', () => {
  const path = '/api/v1/hotspot-candidates';

  async function makeHeaders(body: Uint8Array, overrides: Record<string, string> = {}) {
    const headers = await signRequest(KEYS, 'cf-hotspot-v1', 'POST', path, body);
    return { ...headers, ...overrides };
  }

  it('accepts a correctly signed request', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body);
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: true, keyId: 'cf-hotspot-v1' });
  });

  it('rejects wrong method as invalid_request', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body);
    const result = await verifyRequest({
      keys: KEYS,
      method: 'GET',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.invalid_request });
  });

  it('rejects non-JSON content type as unsupported_media_type', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body, { 'Content-Type': 'text/plain' });
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.unsupported_media_type });
  });

  it('rejects oversized body as payload_too_large', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body);
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 5
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.payload_too_large });
  });

  it('rejects unknown key id', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body, { 'X-AA-Key-Id': 'unknown-key' });
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.unknown_key_id });
  });

  it('rejects expired timestamp', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body, { 'X-AA-Timestamp': '2000-01-01T00:00:00Z' });
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.timestamp_expired });
  });

  it('rejects invalid nonce as invalid_request', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body, { 'X-AA-Nonce': 'not-a-uuid' });
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.invalid_request });
  });

  it('rejects tampered body as invalid_signature', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    const headers = await makeHeaders(body);
    const tampered = new TextEncoder().encode('{"a":2}');
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body: tampered,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.invalid_signature });
  });

  it('rejects wrong secret (invalid_signature) during key rotation', async () => {
    const body = new TextEncoder().encode('{"a":1}');
    // Signed with a different secret than the one currently mapped.
    const headers = await signRequest(
      { 'cf-hotspot-v1': 'wrong-secret' },
      'cf-hotspot-v1',
      'POST',
      path,
      body
    );
    const result = await verifyRequest({
      keys: KEYS,
      method: 'POST',
      path,
      body,
      headers,
      toleranceSeconds: 300,
      maxBodyBytes: 262144
    });
    expect(result).toEqual({ ok: false, code: ERROR_CODES.invalid_signature });
  });
});
